apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtqvi9323-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtqvi9323-tenant-component
    app.kubernetes.io/part-of: loadtqvi9323-tenant-app
  name: loadtqvi9323-tenant-component
  namespace: loadtqvi9323-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtqvi9323-tenant-component
    weight: null
status: {}
